name: Frontend CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Get repo code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Log to azure ACR(container registry)
        uses: azure/docker-login@83efeb77770c98b620c73055fbb59b2847e17dc0 # v1
        with:
          login-server: nexoregistryheczko.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build docker image
        run: |
          docker build -t nexoregistryheczko.azurecr.io/frontend-nexo:latest .
          docker push nexoregistryheczko.azurecr.io/frontend-nexo:latest